version: '3.9'

services:
  database:
    image: postgis/postgis
    container_name: geo_database
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=geodb
      - POSTGRES_PASSWORD=k76XHYH7vHP4tbgf9zVLseVXlJ0UQg89
      - POSTGRES_DB=geodb
    # volumes:
    #   - pgdata:/data/postgres
    # - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql

  app:
    build: backend/.
    command: sh -c "/wait; npm i; npx prisma migrate deploy; npx prisma generate; npx prisma db seed; npm run dev"
    container_name: geo_backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/app
    links:
      - database
    depends_on:
      - database
    environment:
      - 'WAIT_HOSTS=database:5432'
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=15
